DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS users_events;
DROP TABLE IF EXISTS event_requests;

CREATE TABLE users (
	id INT NOT NULL AUTO_INCREMENT,
	first_name VARCHAR(64) NOT NULL,
	last_name VARCHAR(64) NOT NULL,
	email VARCHAR(255) NOT NULL,
	city VARCHAR(64) NOT NULL,
	state VARCHAR(32) NOT NULL,
	bday DATE NOT NULL,
	gender CHAR(1) NOT NULL,
	password VARCHAR(64) NOT NULL,
	PRIMARY KEY (id)
);

CREATE TABLE events(
	id INT PRIMARY KEY AUTO_INCREMENT,
	title VARCHAR(64) NOT NULL,
	description VARCHAR(1024) NOT NULL,
	address VARCHAR(64) NOT NULL,
	city VARCHAR(64) NOT NULL,
	state VARCHAR(32) NOT NULL,
	zip VARCHAR(32) NOT NULL,
	startDate DATE,
	endDate DATE,
	startTime TIME,
	endTime TIME,
	upperAge INT,
	lowerAge INT,
	gender VARCHAR(16),
	FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE
);

CREATE TABLE users_events(
	id INT PRIMARY KEY AUTO_INCREMENT,
	user_id INT NOT NULL,
	event_id INT NOT NULL,
	FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
	FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE
);

CREATE TABLE event_requests(
	id INT PRIMARY KEY AUTO_INCREMENT,
	user_id INT NOT NULL,
	event_id INT NOT NULL,
	FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
	FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE
);
